version: '2'
services:
  pxeboot:
    build: .
    environment:
      - PXE_DHCP_SUBNET=192.168.178.0
    ports:
      - "67:67/udp"
      - "69:69/udp"
      - "4011:4011/udp"
    network_mode: "host"
